language: python
python:
    - "3.8"

services:
  - redis-server

install:
    - pip install -r server/requirements.txt
    - npm -g install jshint

script:
    - jshint clients/chrome/ --exclude="clients/chrome/js/jquery.js"
    - cd server
    - cp .env.test .env
    - flake8
    - ./manage.py test
