# Generated by Django 3.0.5 on 2020-04-19 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('velvet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='url',
            field=models.URLField(db_index=True, max_length=511),
        ),
    ]
